SELECT ?itemLabel ?tag (COUNT(?superClass) AS ?count) WHERE {
  VALUES ?title {
    "שבועון"@he
    "קונדה נאסט (קבוצת מדיה)"@he
    "דייוויד רמניק"@he
    "אנגלית אמריקנית"@he
    "ניו יורק"@he
    "2017"@he
    "ארצות הברית"@he
    "1925"@he
    "אנגלית"@he
    "כתב עת"@he
    "ארצות הברית"@he
    "ניו יורק"@he
    "ביקורת אומנות"@he
    "מסה (חיבור עיוני)"@he
    "שירה"@he
    "סיפורת"@he
    "ניו יורק"@he
    "קריקטורה"@he
    "17 בפברואר"@he
    "1925"@he
    "21 בפברואר"@he
    "ניו יורק טיימס"@he
    "הומור"@he
    "לייף"@he
    "1951"@he
    "מלחמת העולם השנייה"@he
    "הירושימה"@he
    "המאה העשרים"@he
    "המאה העשרים ואחת"@he
    "אליס מונרו"@he
    "הארוקי מורקמי"@he
    "ולדימיר נבוקוב"@he
    "פיליפ רות"@he
    "ג'רום דייוויד סלינג'ר"@he
    "ג'ון אפדייק"@he
    "ריצ'רד ייטס"@he
    "שירלי ג'קסון"@he
    "סוריאליזם"@he
    "אוונגליזם"@he
    "תסמונת מינכהאוזן באמצעות שליח"@he
    "אברהם בורג"@he
    "ארנסט המינגוויי"@he
    "מרלון ברנדו"@he
    "הוליווד"@he
    "מתמטיקה"@he
    "ויליאם שון"@he
    "1951"@he
    "1987"@he
    "רוברט גוטליב"@he
    "1987"@he
    "1992"@he
    "טינה בראון"@he
    "1992"@he
    "1998"@he
    "צבע"@he
    "ניו יורק טיימס"@he
    "צילום"@he
    "1985"@he
    "1998"@he
    "שנות התשעים"@he
    "אינטרנט"@he
    "iPad"@he
    "מלקולם גלדוול"@he
    "וולפראם אלפא"@he
    "2008"@he
    "2003"@he
    "קליפורניה"@he
    "2005"@he
    "כתב עת"@he
    "משק הבית"@he
    "ארצות הברית"@he
    "פוליטיקה"@he
    "כתב עת"@he
    "מפלגה"@he
    "ארצות הברית"@he
    "2004"@he
    "ג'ון קרי"@he
    "ג'ורג' ווקר בוש"@he
    "1 בנובמבר"@he
    "מאמר מערכת"@he
    "2008"@he
    "המפלגה הדמוקרטית"@he
    "ברק אובמה"@he
    "המפלגה הרפובליקנית"@he
    "ג'ון מקיין"@he
    "פיגועי 11 בספטמבר"@he
    "2001"@he
    "קריקטוריסט"@he
    "ארט ספיגלמן"@he
    "שחור"@he
    "מגדלי התאומים"@he
    "אור"@he
    "סימור הרש"@he
    "מלחמת עיראק"@he
    "כלא אבו גרייב"@he
    "מחלקת ההגנה של ארצות הברית"@he
    "איראן"@he
    "קריקטורה"@he
    "1956"@he
    "1958"@he
    "1973"@he
    "1993"@he
    "כתב עת"@he
    "1998"@he
    "הומור"@he
    "צ'ארלס אדמס"@he
    "סול סטיינברג"@he
    "לייזה דונלי"@he
    "ויליאם סטייג"@he
    "איור"@he
    "רי אירווין"@he
    "כובע צילינדר"@he
    "פרפר"@he
    "מונוקל"@he
    "קורי פורד"@he
    "8 באוגוסט"@he
    "מכנסיים"@he
    "פראק"@he
    "מקסיקו"@he
    "פסיק"@he
    "מלחציים"@he
    "כתב נטוי"@he
    "ים סרגסו"@he
    "דיונון"@he
    "דיו"@he
    "נייר"@he
    "1882"@he
    "בד"@he
    "קמע"@he
    "21 בפברואר"@he
    "סול סטיינברג"@he
    "29 במרץ"@he
    "1976"@he
    "מפה"@he
    "מנהטן"@he
    "השדרה התשיעית"@he
    "השדרה העשירית"@he
    "נהר הדסון"@he
    "ארצות הברית"@he
    "ניו יורק"@he
    "ניו ג'רזי"@he
    "לוס אנג'לס"@he
    "וושינגטון די. סי."@he
    "לאס וגאס"@he
    "קנזס סיטי"@he
    "שיקגו"@he
    "טקסס"@he
    "יוטה"@he
    "נברסקה"@he
    "ניו ג'רזי"@he
    "האוקיינוס השקט"@he
    "הרפובליקה העממית של סין"@he
    "יפן"@he
    "רוסיה"@he
    "דימוי עצמי"@he
    "מוסקבה על ההדסון"@he
    "1984"@he
    "זכויות יוצרים"@he
    "סרטי קולומביה"@he
    "טרומן קפוטה (סרט)"@he
    "2005"@he
    "ידוע לשמצה"@he
    "2006"@he
    "פגוש אותי בסנט לואיס"@he
    "1944"@he
    "1968"@he
    "ברט לנקסטר"@he
    "חטאי מלחמה"@he
    "בריאן דה פלמה"@he
    "1989"@he
    "אדפטיישן"@he
    "צ'ארלי קאופמן"@he
    "2002"@he
    "הר ברוקבק"@he
    "2005"@he
    "13 באוקטובר"@he
    "1997"@he
    "2007"@he
    "סיפור קצר"@he
    "קנדה"@he
    "2007"@he
    "אליס מונרו"@he
    "סיינפלד"@he
    "משפחת סימפסון"@he
    "בגידה (זוגיות)"@he
    "חברים"@he
    "צ'נדלר בינג"@he
    "אדפטיישן"@he
    "2002"@he
    "גנב הסחלבים"@he
    "סוזן אורלין"@he
    "2003"@he
    "השטן לובשת פראדה"@he
    "סקס והעיר הגדולה"@he
    "אנימציה"@he
    "דן קווייל"@he
    "פרייז'ר"@he
    "מבקר מוזיקה"@he
    "הייקו"@he
  }
  VALUES ?superClass {
    wd:Q5
    wd:Q95074
    wd:Q49773
    wd:Q1530022
    wd:Q41710
    wd:Q811979
    wd:Q121359
    wd:Q783794
    wd:Q15642541
    wd:Q486972
    wd:Q28108
    wd:Q27096220
    wd:Q13418847
    wd:Q8065
    wd:Q1656682
    wd:Q350604
    wd:Q17537576
    wd:Q732577
    wd:Q3150005
    wd:Q315
    wd:Q17376908
    wd:Q577
    wd:Q3186692
    wd:Q14795564
    wd:Q1790144
  }
  ?sitelink schema:about ?item;
    schema:isPartOf <https://he.wikipedia.org/>;
    schema:name ?title.
  ?item (wdt:P31/(wdt:P279*)) ?superClass.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "he". }
  BIND(COALESCE(IF((?superClass = wd:Q5) || (?superClass = wd:Q95074), "PERSON", 1  / 0 ), IF(((?superClass = wd:Q49773) || (?superClass = wd:Q1530022)) || (?superClass = wd:Q41710), "NORP", 1  / 0 ), IF((?superClass = wd:Q811979) || (?superClass = wd:Q121359), "FAC", 1  / 0 ), IF(?superClass = wd:Q783794, "ORG", 1  / 0 ), IF(((?superClass = wd:Q15642541) || (?superClass = wd:Q486972)) || (?superClass = wd:Q28108), "GPE", 1  / 0 ), IF(?superClass = wd:Q27096220, "LOC", 1  / 0 ), IF((((?superClass = wd:Q13418847) || (?superClass = wd:Q8065)) || (?superClass = wd:Q1656682)) || (?superClass = wd:Q350604), "EVENT", 1  / 0 ), IF((?superClass = wd:Q17537576) || (?superClass = wd:Q732577), "WORK_OF_ART", 1  / 0 ), IF(?superClass = wd:Q3150005, "LAW", 1  / 0 ), IF((?superClass = wd:Q315) || (?superClass = wd:Q17376908), "LANGUAGE", 1  / 0 ), IF((((?superClass = wd:Q577) || (?superClass = wd:Q3186692)) || (?superClass = wd:Q14795564)) || (?superClass = wd:Q1790144), "DATE", 1  / 0 )) AS ?tag)
}
GROUP BY ?itemLabel ?tag